### ISSUE TITLE
fix: better highlight to show selected node

### ISSUE THREAD

**Issue by transmissions11** [paradigmxyz/flux#53]
this red highlight does a great job of making it extremely clear which node you've selected which is helpful for navigation

<img width="756" alt="Screenshot 2023-04-02 at 5 10 11 PM" src="https://user-images.githubusercontent.com/26209401/229386567-94f22cbc-dcb9-4dce-ac75-489af01032d3.png">

but its ugly and doesnt match the rest of our color scheme

open to suggestions on a design that looks decent but still makes it super clear which node you've selected

**Comment by AdamSchinzel** [comment]
Will try to polish it

**Comment by h0tw4t3r** [comment]
Gray or Black? Tbh I have no issues with the selection being red. Usually, I don't have things selected, and red raises my attention with ease.

**Comment by AdamSchinzel** [comment]
Just want to let I will have time to work on this on weekend, if someone wants he can pick it up
