### ISSUE TITLE
fix: while responses are being generated, copy code buttons become difficult to click

### ISSUE THREAD

**Issue by transmissions11** [paradigmxyz/flux#70]
**Platform**
OSX Chrome

**Description**
While a response is being streamed in, if there is a codeblock with a copy code button, clicking on it will seem to do nothing or require many clicks.

I believe this is because the button is being re-rendered on every new token? Regardless, should always be easy to click the button whether text is generating or not.

**Comment by ai-slave** [comment]
Getting annoyed with this one also, will try to tackle now

**Comment by DJRHails** [comment]
Sorry if I duplicated work @ai-slave, got fed up of this as well.
