### ISSUE TITLE
feat: Whisper speech-to-text

### ISSUE THREAD

**Issue by ghgoodreau** [paradigmxyz/flux#72]
**Is your feature request related to a problem? Please describe.**
It would be helpful to add whisper support to allow users to transcribe their speech to text, as some users may prefer this option. 

**Describe the solution you'd like**
A microphone button (and maybe a keybind) that will allow users to utilize speech-to-text when prompting LLMs. Still researching different ways to accomplish this but it should be relatively straightforward to implement.

**Describe alternatives you've considered**
Whisper makes the most sense because you can use the same API key. Other options can be researched later, possibly when adding #71 support.

**Additional context**
You can go ahead and assign this to me @transmissions11 just opening it for tracking purposes. I'll also open a draft PR once I start coding so it's visible early on.

**Comment by nmandal** [comment]
I would like to help contribute! I can take this one if you'd like.
