### ISSUE TITLE
feat: change keybinding for remove node from command + backspace

### ISSUE THREAD

**Issue by d1onys1us** [paradigmxyz/flux#80]
**Is your feature request related to a problem? Please describe.**
Yes, as a mac user I often use command + backspace to delete the current line. 

**Describe the solution you'd like**
Change from command + backspace to something equally ergonomic. I'm new to the tool, so I would prefer whatever is pragmatic in the context of the other keybindings.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by transmissions11** [comment]
yeahhhh i do this too, tho have been struggling to think of a better delete key. could maybe use command + shift + delete and find another keybind for delete all
