### ISSUE TITLE
`npm install && npm run dev` does not work

### ISSUE THREAD

**Issue by gwpl** [paradigmxyz/flux#92]
**Platform**
Arch Linux.

**Description**

```
$ npm install
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path ~/github/paradigmxyz/flux/node_modules/framer-motion
npm ERR! dest ~/github/paradigmxyz/flux/node_modules/.framer-motion-dgXQO1g6
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '~/github/paradigmxyz/flux/node_modules/framer-motion' -> '~/github/paradigmxyz/flux/node_modules/.framer-motion-dgXQO1g6'

npm ERR! A complete log of this run can be found in: ~/.npm/_logs/2023-11-27T15_17_03_730Z-debug-0.log
$ npm run dev

> flux@0.0.0 dev
> vite

sh: line 1: vite: command not found
$ # npm@10.2.4
```

I am not javascript/typescript/npm expert. Also log that npm pointed out did not exist 🤷🏻 , otherwise I would include relevant data.

(Apart from fixing, maybe provide `Vagrantfile` or `Dockerfile` with [[maximum isolation]](https://github.com/AntonOsika/gpt-engineer/issues/747) so (Linux) users can also just build and run in isolation ?)

**Comment by transmissions11** [comment]
this does not appear to be a flux issue, would suggest running `rm -rf node_modules/`, trying again, and if you still have issues consulting stackoverflow, or chatgpt :/
