### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by chrisribe** [paradigmxyz/flux#97]
**Platform**
The OS and browser you're using.
Win/Chrome 

**Description**
main https://flux.paradigm.xyz/ api key entry dialog stays open after pasting it in.
There is no ok button, enter does nothing

[short summary of the bug]

I tried doing this:
Tried edge browser.

[screenshot or video that causes the bug]
![image](https://github.com/paradigmxyz/flux/assets/1999791/5fff7c72-6271-415b-89c4-f98244a2b3a4)

I expected to see this happen: [explanation]
Expected the dialog to close on paste, enter or other.

Instead, this happened: [explanation]
Dialog stays open, only after going into dom and deleting overlay can you kinda test it out

**Comment by AshishGapat** [comment]
This is probably due to OpenAI's new project keys that start with `sk-proj-` instead of `sk-` causing validation to fail
